export interface Avatar {
    name: string;
    url: string;
}

export const Avatars: Avatar[] = [
    { name: "aaron", url: "https://play.pokemonshowdown.com/sprites/trainers/aaron.png" },
    { name: "acerola", url: "https://play.pokemonshowdown.com/sprites/trainers/acerola.png" },
    { name: "alain", url: "https://play.pokemonshowdown.com/sprites/trainers/alain.png" },
    { name: "alder", url: "https://play.pokemonshowdown.com/sprites/trainers/alder.png" },
    { name: "archer", url: "https://play.pokemonshowdown.com/sprites/trainers/archer.png" },
    { name: "ash", url: "https://play.pokemonshowdown.com/sprites/trainers/ash.png" },
    { name: "barry", url: "https://play.pokemonshowdown.com/sprites/trainers/barry.png" },
    { name: "bea", url: "https://play.pokemonshowdown.com/sprites/trainers/bea.png" },
    { name: "bede", url: "https://play.pokemonshowdown.com/sprites/trainers/bede.png" },
    { name: "blue", url: "https://play.pokemonshowdown.com/sprites/trainers/blue.png" },
    { name: "brock", url: "https://play.pokemonshowdown.com/sprites/trainers/brock.png" },
    { name: "bruno", url: "https://play.pokemonshowdown.com/sprites/trainers/bruno.png" },
    { name: "caitlin", url: "https://play.pokemonshowdown.com/sprites/trainers/caitlin.png" },
    { name: "candice", url: "https://play.pokemonshowdown.com/sprites/trainers/candice.png" },
    { name: "clair", url: "https://play.pokemonshowdown.com/sprites/trainers/clair.png" },
    { name: "cynthia", url: "https://play.pokemonshowdown.com/sprites/trainers/cynthia.png" },
    { name: "dawn", url: "https://play.pokemonshowdown.com/sprites/trainers/dawn.png" },
    { name: "elesa", url: "https://play.pokemonshowdown.com/sprites/trainers/elesa.png" },
    { name: "erika", url: "https://play.pokemonshowdown.com/sprites/trainers/erika.png" },
    { name: "ethan", url: "https://play.pokemonshowdown.com/sprites/trainers/ethan.png" },
    { name: "fantina", url: "https://play.pokemonshowdown.com/sprites/trainers/fantina.png" },
    { name: "flannery", url: "https://play.pokemonshowdown.com/sprites/trainers/flannery.png" },
    { name: "gardenia", url: "https://play.pokemonshowdown.com/sprites/trainers/gardenia.png" },
    { name: "giovanni", url: "https://play.pokemonshowdown.com/sprites/trainers/giovanni.png" },
    { name: "gloria", url: "https://play.pokemonshowdown.com/sprites/trainers/gloria.png" },
    { name: "grimsley", url: "https://play.pokemonshowdown.com/sprites/trainers/grimsley.png" },
    { name: "guzma", url: "https://play.pokemonshowdown.com/sprites/trainers/guzma.png" },
    { name: "hau", url: "https://play.pokemonshowdown.com/sprites/trainers/hau.png" },
    { name: "hop", url: "https://play.pokemonshowdown.com/sprites/trainers/hop.png" },
    { name: "iris", url: "https://play.pokemonshowdown.com/sprites/trainers/iris.png" },
    { name: "jasmine", url: "https://play.pokemonshowdown.com/sprites/trainers/jasmine.png" },
    { name: "korrina", url: "https://play.pokemonshowdown.com/sprites/trainers/korrina.png" },
    { name: "lana", url: "https://play.pokemonshowdown.com/sprites/trainers/lana.png" },
    { name: "leon", url: "https://play.pokemonshowdown.com/sprites/trainers/leon.png" },
    { name: "lillie", url: "https://play.pokemonshowdown.com/sprites/trainers/lillie.png" },
    { name: "lusamine", url: "https://play.pokemonshowdown.com/sprites/trainers/lusamine.png" },
    { name: "marnie", url: "https://play.pokemonshowdown.com/sprites/trainers/marnie.png" },
    { name: "may", url: "https://play.pokemonshowdown.com/sprites/trainers/may.png" },
    { name: "misty", url: "https://play.pokemonshowdown.com/sprites/trainers/misty.png" },
    { name: "n", url: "https://play.pokemonshowdown.com/sprites/trainers/n.png" },
    { name: "nessa", url: "https://play.pokemonshowdown.com/sprites/trainers/nessa.png" },
    { name: "oak", url: "https://play.pokemonshowdown.com/sprites/trainers/oak.png" },
    { name: "olivia", url: "https://play.pokemonshowdown.com/sprites/trainers/olivia.png" },
    { name: "piers", url: "https://play.pokemonshowdown.com/sprites/trainers/piers.png" },
    { name: "red", url: "https://play.pokemonshowdown.com/sprites/trainers/red.png" },
    { name: "roxie", url: "https://play.pokemonshowdown.com/sprites/trainers/roxie.png" },
    { name: "serena", url: "https://play.pokemonshowdown.com/sprites/trainers/serena.png" },
    { name: "skyla", url: "https://play.pokemonshowdown.com/sprites/trainers/skyla.png" },
    { name: "steven", url: "https://play.pokemonshowdown.com/sprites/trainers/steven.png" },
    { name: "wallace", url: "https://play.pokemonshowdown.com/sprites/trainers/wallace.png" },
    { name: "wally", url: "https://play.pokemonshowdown.com/sprites/trainers/wally.png" },
    { name: "worker", url: "https://play.pokemonshowdown.com/sprites/trainers/worker.png" },
];
