type PokemonSpriteChoice =
    | "Pokémon Showdown"
    | "Red & Blue"
    | "Yellow"
    | "Crystal"
    | "Gold"
    | "Silver"
    | "Emerald"
    | "Ruby & Sapphire"
    | "FireRed & LeafGreen"
    | "Diamond & Pearl"
    | "Platinum"
    | "HeartGold & SoulSilver"
    | "Black & White"
    | "Black & White (Animated)"
    | "Omega Ruby & Alpha Sapphire"
    | "X & Y"
    | "Ultra Sun & Ultra Moon"
    | "Gen VIII Icons";
